base: &base
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: vagrant
  password: vagrant

production:
  <<: *base
  database: gitlabhq_production


development:
  <<: *base
  database: gitlabhq_development

test:
  <<: *base
  database: gitlabhq_test
